# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/VivadoCodigos/EsteiraIndustrial_MiniControladorDigital/EsteiraIndustrial_MiniControladorDigital.cache/wt [current_project]
set_property parent.project_path D:/VivadoCodigos/EsteiraIndustrial_MiniControladorDigital/EsteiraIndustrial_MiniControladorDigital.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib D:/VivadoCodigos/EsteiraIndustrial_MiniControladorDigital/EsteiraIndustrial_MiniControladorDigital.srcs/sources_1/new/EsteiraIndustrial.vhd
synth_design -top controlador_esteira -part xc7a100tcsg324-1
write_checkpoint -noxdef controlador_esteira.dcp
catch { report_utilization -file controlador_esteira_utilization_synth.rpt -pb controlador_esteira_utilization_synth.pb }
